apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-deployment
spec:
  selector:
    matchLabels:
      app: capstone
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 4
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
      - name: nginx
        image: uclabruin87/capstone:latest
        ports:
        - containerPort: 80
